# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile

# Secret key
play.http.secret.key="plantshopplayframeworksecretkey1234567890abcdef"

# Database
db.default.driver=org.postgresql.Driver
db.default.url="jdbc:postgresql://localhost:5432/plant_shop_play_framework"
db.default.username="tilnede0x1182"
db.default.password="tilnede0x1182"

# Ebean
ebean.default=["models.*"]

# Evolutions automatiques
play.evolutions.db.default.autoApply=true

# CSRF : actif globalement, desactive par route via + nocsrf dans conf/routes

# Server
play.server.http.port=4500
